# Window sizes and visibility
if PLAT_WIN
	position.left=100
	position.top=0
if PLAT_GTK
	position.left=5
	position.top=22
position.width=$(scale 900)
position.height=$(scale 900)

statusbar.visible=1
tabsize=4
indent.size=4
use.tabs=0
line.margin.visible=1
